### ISSUE TITLE
save_image.py dosen't work

### ISSUE THREAD

**Issue by seokhyuun** [Jiloc/edsdk-python#3]
Traceback (most recent call last):
  File "C:\Users\33Lab\Documents\Dev\Graduation_project\edsdk-python\examples\save_image.py", line 5, in <module>
    import edsdk
  File "C:\Users\33Lab\Documents\Dev\Graduation_project\edsdk-python\edsdk\__init__.py", line 1, in <module>
    from edsdk.api import *
ModuleNotFoundError: No module named 'edsdk.api'

Process finished with exit code 1

**Comment by TeddyDelrue** [comment]
Hi, 
Same here, I think I did setup as required in the Readme.
@GiChiken, did you find a solution since you got the error ?

**Comment by TrevorChiu** [comment]
Same here any solution to this...

**Comment by ruolunhui** [comment]
直接打开examples 避免导入源代码里面的sdk模块 因为已经安装过edsdk-python包 重复了
